# The buildscript for travis ci verification
# Execute on ubuntu xenial using docker
language: c++

sudo: required

services:
  - docker

before_install:
  - docker pull ubuntu:17.10
  - docker run -w /root --name test -d ubuntu:17.10 sleep infinity
  - docker cp . test:/root/

install:
  - docker exec test apt-get update
  - docker exec test apt-get install -y cmake qt5-default qttools5-dev-tools qtconnectivity5-dev g++ xvfb

script:
  - docker exec -t test bash -ic "mkdir build"
  - docker exec -t test bash -ic "cd build && cmake ../src && make"
#  - docker exec -t test bash -ic "cd build && xvfb-run make test"